# Generated by Django 4.2.6 on 2025-11-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0010_website_add_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
