# Generated by Django 4.2.6 on 2025-11-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0011_delete_service'),
    ]

    operations = [
        migrations.AddField(
    model_name='services',
    name='slug',
    field=models.SlugField(blank=True, null=True, unique=True),
),

    ]
