# Generated by Django 4.2.6 on 2025-11-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0012_services_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
