# Generated by Django 4.2.6 on 2025-11-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0013_alter_services_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
