# Generated by Django 4.2.6 on 2025-11-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0014_website_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='videos',
            field=models.TextField(blank=True, help_text='Add video URLs separated by commas or paste iframe embed codes', null=True),
        ),
    ]
