# Generated by Django 4.2.6 on 2025-11-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0015_alter_website_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
