# Generated by Django 4.2.6 on 2025-11-24 05:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0016_services_meta_description_services_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
