# Generated by Django 4.2.6 on 2025-11-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0017_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
