# Generated by Django 4.2.6 on 2025-11-27 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0019_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Train FAQ',
                'verbose_name_plural': 'Train FAQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Train Service',
                'verbose_name_plural': 'Train Services',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='FAQS',
        ),
        migrations.AddField(
            model_name='trainfaq',
            name='train_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='vynzora_app.trainservice'),
        ),
    ]
