# Generated by Django 4.2.6 on 2025-11-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0020_trainfaq_trainservice_delete_faqs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('description', models.TextField(max_length=300)),
                ('point1', models.CharField(max_length=150)),
                ('point2', models.CharField(max_length=150)),
                ('point3', models.CharField(max_length=150)),
                ('point4', models.CharField(max_length=150)),
                ('point5', models.CharField(max_length=150)),
                ('point6', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
