# Generated by Django 4.2.6 on 2025-12-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0021_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainservice',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trainservice',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title', max_length=255, null=True),
        ),
    ]
